cluster_config_path = "~/.kube/config"
entitled_registry_user_email = "kskhong@au1.ibm.com"
entitled_registry_key = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJJQk0gTWFya2V0cGxhY2UiLCJpYXQiOjE2MzUyMjYxODgsImp0aSI6IjViODdiOGNhZWIwZDQzMmFiNmMwNDM5NGZkZGJkOWE2In0.IBzNGOK9KmWGTWGTo0cA27hJ4-z0XAWlS9Zo8apQqTo"
storageclass = "ocs-storagecluster-cephfs"
cp4i_version = "2021.3.1"
cp4i_channel_version = "v1.4"
cp4i_license = "L-RJON-C5CSNH"